# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: echo 'before build'

  publish-npm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --local user.email "18570148691@163.com"
          git config --local user.name "GGwujun"
          git checkout $CI_COMMIT_REF_NAME
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@winfe"
          npm config list
          yarn install
          SPACE_CHAR=" "
          npx standard-version --releaseCommitMessageFormat "chore(release):${SPACE_CHAR}{{currentTag}} [skip ci]"
          git push --follow-tags origin $CI_COMMIT_REF_NAME
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUB_NPM_ACCESS_TOKEN}}
